name: Publish to NPM

# git tag v1.0.0
# git push origin v1.0.0

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code with submodules
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Force HTTPS for Git URLs
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@lambdapay"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Publish to npm
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
